### PR TITLE
Adding a temporary DMSIM_t Uber model

### PR DESCRIPTION
**Pull request by BFuks**
First UFO model and documentation. I am currently extending the documentation and adding the complex scalar case. I will commit the FeynRules file when finalised.

### CODE REVIEW

**Comment by cohm** [comment]
Thanks, @BFuks! Just a thought while this is still WIP: would you mind adding the (unzipped) code instead? That would make it much easier to review any changes through diffs. Ideally also markdown (`.md`) or .tex for the doc too - but that's less important, I'd say.

Thanks a lot for putting this together!

Best,
Christian

**Comment by obrandt1** [comment]
Hi @BFuks ! I agree with @cohm , it would be good to have unzipped code here. Once we have this, we give the pull request the OK and then we can iterate further (FeynRules etc). 
Does this sound reasonable?

**Comment by BFuks** [comment]
Hi Oleg,

I have replaced the tarball accordingly. I will add the tex file later on as I am still working on it to add important features crucial for NLO simulations (and for now, it is too partial to be shared).

Cheers,

Benjamin

**Comment by obrandt1** [comment]
Hi @BFuks , 

Many thanks! Merging this now. 

Do I understand correctly that the UFO as it is in the repository now can already be used at LO by the LHC DM WG collaborators?

Many thanks,

     Oleg

**Comment by BFuks** [comment]
Yes it can.

Cheers,

B>

**Pull request merged**
